version: 0.2

phases:
  pre_build:
    commands:
      - cd ./Customer
      - ls
      - aws sts get-caller-identity
#      - mvn spring-boot:build-image -DskipTests
#      - docker image ls
#      - docker tag volanscoe:latest 608100859042.dkr.ecr.us-east-1.amazonaws.com/volanscoe:latest
  
  build:
    commands:
      - echo 'PUSHING'
      - $(aws ecr get-login --no-include-email)
#      - docker push 608100859042.dkr.ecr.us-east-1.amazonaws.com/volanscoe:latest
      - echo 'PUSHED'
      - aws eks update-kubeconfig --name test-cluster
      - aws sts get-caller-identity
      - kubectl get all
      - kubectl apply -f ./deployment.yaml
      - echo 'Done'