version: 0.2

phases:
  pre_build:
    commands:
      - echo 'TESTING NOW'
      - mvn --version
      - cd ./Customer
      - ls
      - mvn spring-boot:build-image -DskipTests
  
  build:
    commands:
      - echo 'TEST'