version: 0.2

phases:
  pre_build:
    commands:
      - echo 'TESTING NOW'
      - mvn --version
      - cd ./Customer
      - ls
      - mvn spring-boot:build-image -DskipTests
      - docker image ls
      - docker tag customer:0.0.1-SNAPSHOT volanscoe/customer:0.0.1-SNAPSHOT
  
  build:
    commands:
      - echo 'PUSHING'
      - $(aws ecr get-login --no-include-email)
#      - kubectl --version
      - docker push volanscoe/customer:0.0.1-SNAPSHOT
      - echo 'PUSHED'
      - kubectl --version