apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: customer-api
  name: customer-api
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: customer-api
#  strategy:
#    rollingUpdate:
#      maxSurge: 25%
#      maxUnavailable: 25%
#    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customer-api
    spec:
      containers:
      - image: 608100859042.dkr.ecr.us-east-1.amazonaws.com/volanscoe:ver1
        imagePullPolicy: Always
        name: customer
      restartPolicy: Always

